MuliUserBlog_Django/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('',include('user_app.urls')),
    path('api/blog/',include('blog.api.urls')),
]

if settings.DEBUG:

    urlpatterns+= static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )

blog/urls.py
from django.urls import path
from blog import views


app_name = 'blog'

urlpatterns = [

    path('',views.PostListView.as_view(), name = 'blog-home'),
    path('about/',views.about,name = 'blog-about'),
    path('post/<int:pk>/',views.PostDetailView.as_view(), name = 'post-detail'),
    path('post/create/',views.PostCreateView.as_view(),name = 'post-create'),
    path('post/update/<int:pk>/',views.PostUpdatView.as_view(),name = 'post-update'),
    path('post/delete/<int:pk>/',views.PostDeleteView.as_view(),name = 'post-delete'),
    path('user_profile/<username>/',views.UserPostsListView.as_view(),name = 'user-profile-details')


]

user_app/urls.py
from django.urls import path,reverse_lazy
from user_app import views,forms
from django.contrib.auth import views as auth_views

app_name = 'user_app'

urlpatterns = [

    path('register/', views.register_user, name = 'user-registration'),
    path('login/',auth_views.LoginView.as_view(template_name = "user_app/login.html"),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='user_app/logout.html'),name ='logout'),
    path('profile/',views.user_profile,name = 'profile'),
    path('changeinfo/',views.change_user_profile,name = 'changeinfo'),
    path('password_change/',auth_views.PasswordChangeView.as_view(template_name = 'user_app/password_change_form.html',
                                                                  success_url = reverse_lazy('user_app:logout')), name = 'password_change'),

    #if user forgets password

    path('password_reset/',auth_views.PasswordResetView.as_view(template_name = "user_app/password_reset_form.html",
                                          success_url = reverse_lazy("user_app:password_reset_done"),email_template_name = "user_app/password_reset_email.html",
                                            form_class = forms.ForgotPasswordForm ,subject_template_name = "user_app/password_reset_subject.txt"),
                                        name = 'password_reset'),



    path('password_reset_done/',auth_views.PasswordResetDoneView.as_view(template_name = "user_app/password_reset_done.html"),
         name ='password_reset_done'),


    path('password_reset_confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name = 'user_app/password_reset_confirm.html',
                                              success_url = reverse_lazy("user_app:login")), name = 'password_reset_confirm'),

]

user_app/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(default='default.jpg', upload_to="profile_pics")

    def __str__(self):
        return self.user.username + " profile"

    def save(self):

        super().save()
        img = Image.open(self.profile_pic.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.profile_pic.path)

user_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,PasswordResetForm
from django.contrib.auth.models import User
from user_app.models import UserProfile
from django import forms




class RegistrationForm(UserCreationForm):


    email = forms.EmailField(required=True)


    def __init__(self, *args, **kwargs):

        super(UserCreationForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

    class Meta:
        model = User
        fields = ['username','email','password1' ,'password2']


class ChangeProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ['profile_pic']

        labels = {

            'profile_pic' : "profile picture"
        }


class ChangeUserStngsForm(forms.ModelForm):

    email = forms.EmailField(required = True)

    class Meta:
        model = User
        fields = ['username' , 'email']





class ForgotPasswordForm(PasswordResetForm):


    def clean_email(self):

        email = self.cleaned_data['email']

        if not User.objects.filter(email__iexact= email).exists():
            raise forms.ValidationError("there's no user that uses that email")
        return email

user_app/views.py
from django.shortcuts import render,redirect
from user_app.forms import RegistrationForm,ChangeProfileForm,ChangeUserStngsForm
from django.contrib import messages
import user_app.models as user_models
from django.contrib.auth.decorators import login_required

# Create your views here.

def register_user(request):

    if request.method == "POST":

        registration_form = RegistrationForm(request.POST)

        if registration_form.is_valid():
            new_user = registration_form.save()
            username = registration_form.cleaned_data.get('username')
            user_profile = user_models.UserProfile(user = new_user)
            user_profile.save()
            messages.success(request, username + " registered successfully")
            return redirect('user_app:login')
    else:

        registration_form = RegistrationForm()

    return render(request,"user_app/register.html",context = {"registration_form" : registration_form} )

@login_required
def user_profile(request):

    return render(request,"user_app/user_profile.html")


@login_required
def change_user_profile(request):


    if request.method == 'POST':

        change_userprofile_form = ChangeProfileForm(request.POST,request.FILES,instance = request.user.userprofile)
        change_userstngs_form = ChangeUserStngsForm(request.POST,instance = request.user)

        if change_userprofile_form.is_valid() and change_userstngs_form.is_valid():

            change_userprofile_form.save()
            change_userstngs_form.save()
            return redirect('user_app:profile')

    else:

        change_userprofile_form = ChangeProfileForm(instance = request.user.userprofile)
        change_userstngs_form = ChangeUserStngsForm(instance = request.user)


    return render(request,"user_app/change_user_profile.html",
                  context = { "change_userprofile_form" : change_userprofile_form , "change_userstngs_form" : change_userstngs_form})

user_app/templates/user_app/change_user_profile.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}


{% block content %}

    <form method="POST" enctype="multipart/form-data">

        {% csrf_token %}

         {{change_userstngs_form | crispy }}

         {{change_userprofile_form | crispy }}




        <input type="submit" class="btn btn-success">

    </form>

{% endblock%}

user_app/templates/user_app/login.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags%}
{%block content %}

  <form method="POST">

       {% csrf_token %}
      {{form | crispy }}


      <input class="btn btn-success" type="submit" value = "Sign in">

  </form>

  <br>
  <a href="{% url 'user_app:password_reset' %}"> forgot password ?</a>

{% endblock%}

user_app/templates/user_app/logout.html
{%extends 'blog/base.html' %}

{%block content %}

    <div class="alert alert-success">
      you are logged-out
    </div>
  <a role="button" class="btn btn-danger" href="{% url 'user_app:login'%}"> Login again </a>
{%endblock%}

user_app/templates/user_app/password_change_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags%}
{%block content %}

  <form method="POST">

       {% csrf_token %}
      {{form | crispy }}

      <input class="btn btn-success" type="submit" value="Change Password">

  </form>


{% endblock%}

user_app/templates/user_app/password_reset_confirm.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

  <form method="POST">

      {% csrf_token %}

      {{ form | crispy }}

   <input type="submit" class="btn btn-success" value="Reset Password">

  </form>


{% endblock%}

user_app/templates/user_app/password_reset_done.html
{% extends 'blog/base.html' %}


{% block content %}

        <div class="alert alert-success" role="alert">

            An Email has been sent with instructions

        </div>

{% endblock%}

user_app/templates/user_app/password_reset_email.html
        you asked for password reset for email {{ email }}.
        Follow the link below:
        {{ protocol}}://{{ domain }}{% url 'user_app:password_reset_confirm' uidb64=uid token=token %}

user_app/templates/user_app/password_reset_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

  <form method="POST">

      {% csrf_token%}

      {{form | crispy }}

   <input type="submit" class="btn btn-success" value="Submit">

  </form>


{% endblock%}

user_app/templates/user_app/register.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content%}
    <div class="content-section" >
           <form method="POST" >

                {% csrf_token %}
                  {{ registration_form | crispy  }}

               <input class = "btn btn-success" type="submit" value="Register">
           </form>

    </div>
{% endblock %}

user_app/templates/user_app/user_profile.html
{% extends 'blog/base.html' %}

{% block content %}

  <div class="media">

      <img class="rounded-circle account-img" src ="{{ user.userprofile.profile_pic.url }}" >

      <div class="media-body">

            <h2 class="account-heading"> {{ user.username  | title }} </h2>
            <p class="text-secondary"> {{user.email}} </p>
            <a role="button" class="btn btn-warning" href="{% url 'user_app:changeinfo' %}"> Change Personal Info </a>
            <a role="button" class="btn btn-warning" href="{% url 'user_app:password_change' %}"> Change Password </a>

      </div>



  </div>

{% endblock%}