MuliUserBlog_Django/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('',include('user_app.urls')),
    path('api/blog/',include('blog.api.urls')),
]

if settings.DEBUG:

    urlpatterns+= static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )

blog/api/urls.py
from django.urls import path
from . import views,viewsets
from rest_framework.routers import DefaultRouter,SimpleRouter
urlpatterns = [

    path('post/<int:pk>/', views.PostRUDAPIView.as_view(), name='post-rud'),
    path('post/list/',views.PostListAPIView.as_view(),name = 'post-list'),
    path('post/create/',views.PostCreateAPIView.as_view(),name = 'post-create')

]
router = SimpleRouter()
router.register('posts',viewsets.PostCrudAPIViewSet,base_name='posts')
urlpatterns+=router.urls

blog/urls.py
from django.urls import path
from blog import views


app_name = 'blog'

urlpatterns = [

    path('',views.PostListView.as_view(), name = 'blog-home'),
    path('about/',views.about,name = 'blog-about'),
    path('post/<int:pk>/',views.PostDetailView.as_view(), name = 'post-detail'),
    path('post/create/',views.PostCreateView.as_view(),name = 'post-create'),
    path('post/update/<int:pk>/',views.PostUpdatView.as_view(),name = 'post-update'),
    path('post/delete/<int:pk>/',views.PostDeleteView.as_view(),name = 'post-delete'),
    path('user_profile/<username>/',views.UserPostsListView.as_view(),name = 'user-profile-details')


]

user_app/urls.py
from django.urls import path,reverse_lazy
from user_app import views,forms
from django.contrib.auth import views as auth_views

app_name = 'user_app'

urlpatterns = [

    path('register/', views.register_user, name = 'user-registration'),
    path('login/',auth_views.LoginView.as_view(template_name = "user_app/login.html"),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='user_app/logout.html'),name ='logout'),
    path('profile/',views.user_profile,name = 'profile'),
    path('changeinfo/',views.change_user_profile,name = 'changeinfo'),
    path('password_change/',auth_views.PasswordChangeView.as_view(template_name = 'user_app/password_change_form.html',
                                                                  success_url = reverse_lazy('user_app:logout')), name = 'password_change'),

    #if user forgets password

    path('password_reset/',auth_views.PasswordResetView.as_view(template_name = "user_app/password_reset_form.html",
                                          success_url = reverse_lazy("user_app:password_reset_done"),email_template_name = "user_app/password_reset_email.html",
                                            form_class = forms.ForgotPasswordForm ,subject_template_name = "user_app/password_reset_subject.txt"),
                                        name = 'password_reset'),



    path('password_reset_done/',auth_views.PasswordResetDoneView.as_view(template_name = "user_app/password_reset_done.html"),
         name ='password_reset_done'),


    path('password_reset_confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name = 'user_app/password_reset_confirm.html',
                                              success_url = reverse_lazy("user_app:login")), name = 'password_reset_confirm'),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.


class  Post(models.Model):

    title = models.CharField(max_length= 264)
    content = models.TextField()
    date_posted  = models.DateTimeField(default = timezone.now)
    author = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):
        return self.title

blog/api/views.py
from rest_framework.generics import RetrieveUpdateDestroyAPIView,ListAPIView,CreateAPIView
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from blog.api.permissions import IsOwnerOrReadOnly
from blog.models import Post
from blog.api.serializer import PostSerializer



class PostListAPIView(ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

class PostCreateAPIView(CreateAPIView):
    serializer_class = PostSerializer
    queryset = Post.objects.all()

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)


class PostRUDAPIView(RetrieveUpdateDestroyAPIView):

    queryset = Post.objects.all()
    lookup_field = 'pk'
    serializer_class = PostSerializer
    permission_classes = [IsAuthenticatedOrReadOnly,IsOwnerOrReadOnly]

blog/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from blog.models import Post
from django.contrib.auth.models import User
from django.views.generic import (ListView,DetailView,CreateView,
                                  UpdateView,DeleteView)
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin

# Create your views here.


class PostListView(ListView):

    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']


class UserPostsListView(ListView):

    model = Post
    context_object_name = 'posts'
    template_name = "blog/user_profile.html"

    def get_context_data(self,**kwargs):

        context = super().get_context_data(**kwargs)
        user = get_object_or_404(User,username = self.kwargs.get('username'))
        context['profile_owner'] = user
        context['posts'] = Post.objects.filter(author = user)
        return context


class PostDetailView(DetailView):

    model = Post
    context_object_name = 'post'


class PostCreateView(LoginRequiredMixin,CreateView):

    model = Post
    fields = ['title', 'content']
    success_url = reverse_lazy('blog:blog-home')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdatView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):

    model = Post
    fields = ['title', 'content']
    success_url = reverse_lazy('blog:blog-home')

    def test_func(self):
        post = self.get_object()
        return post.author == self.request.user


class PostDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):

    model = Post
    success_url = reverse_lazy('blog:blog-home')
    context_object_name = 'post'

    def test_func(self):
        post = self.get_object()
        return post.author == self.request.user


def about(request):
    return render(request,"blog/about.html")

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block content %}

  <h1> About Page </h1>

{%endblock%}

blog/templates/blog/base.html
<!DOCTYPE html>

{% load staticfiles %}


<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'blog/css/main.css'%}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">


    <title> BLOG </title>

  </head>


  <body>

    <!-- navbar -->
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
   <a class="navbar-brand" href="{% url 'blog:blog-home' %}">BLogMe</a>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ">

      <li class="nav-item nav-link">
        <a class="nav-link" href="{% url 'blog:blog-home'%}">Home</a>
      </li>

      <li class="nav-item nav-link">
        <a class="nav-link" href="{% url 'blog:blog-about'%}">About</a>
      </li>

    </ul>

  </div>
       <!-- Navbar Right Side -->


    <div class="navbar-nav">
     {% if user.is_authenticated %}

        <a class="nav-item nav-link" href="{% url 'blog:user-profile-details' user.username %}"> {{user.username | title }}</a>
        <a class="nav-item nav-link" href="{% url 'blog:post-create' %}"> Create Post </a>
        <a class="nav-item nav-link" href="{% url 'user_app:logout' %}">Logout</a>

     {% else %}

        <a class="nav-item nav-link" href="{% url 'user_app:login' %}">Login</a>
        <a class="nav-item nav-link" href="{% url 'user_app:user-registration' %}">Register</a>

     {% endif %}
    </div>

</nav>
    <!-- end navbar -->
<br>
<main role="main" class="container">
  <div class="row">
    <div class="col-md-8">

       {% if messages %}

          {% for message in messages %}

             <div class="alert alert-{{message.tags}}">

                 {{message}}

             </div>

          {% endfor %}

        {% endif %}

      {% block content %}{% endblock %}
    </div>

  </div>
</main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/blog/home.html
{% extends 'blog/base.html'%}


{% block content %}

    {% if posts %}

        {% for post in posts%}
            <article class="media content-section">
              <div class="media-body">
                <div class="article-metadata">
                  <img class="rounded-circle article-img" src="{{ post.author.userprofile.profile_pic.url }}">
                  <a class="mr-2" href="{% url 'blog:user-profile-details' post.author.username %}">{{ post.author }}</a>
                  <small class="text-muted">{{ post.date_posted }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'blog:post-detail' post.id %}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
              </div>
            </article>
        {% endfor %}


    {% endif %}

{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}


{% block content %}

   <form method="POST">

       {% csrf_token%}

       <h2> Delete Post ( {{ post.title }} ) ??</h2>
        <br>
        <input type="submit" class="btn btn-danger">
        <a role="button" href ="{% url 'blog:post-detail' post.id %}"> Cancel</a>

   </form>


{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html'%}


{% block content %}

   <article class="media content-section">
              <div class="media-body">
                <div class="article-metadata">
                  <img class="rounded-circle article-img" src="{{ post.author.userprofile.profile_pic.url }}">
                  <a class="mr-2" href="{% url 'blog:user-profile-details' post.author.username %}">{{ post.author }}</a>
                  <small class="text-muted">{{ post.date_posted }}</small>
                </div>
                 <br>
                <h2> {{ post.title }} </h2>
                <p class="article-content">{{ post.content }}</p>
              </div>
   </article>

   <div class="container">

       {% if post.author == user %}

          <a role="button" class="btn btn-success" href="{% url 'blog:post-update' post.id %}"> Edit </a>
          <a role="button" class="btn btn-success" href="{% url 'blog:post-delete' post.id %}"> Delete </a>

       {% endif%}

   </div>


{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

  <form method="POST">
      {% csrf_token%}

      {{form | crispy}}

      <input type="submit" class="btn btn-success" value="Post">

  </form>


{% endblock %}

blog/templates/blog/user_profile.html
{% extends 'blog/base.html'%}


{% block content %}

      <div class="media">

          <img class="rounded-circle account-img" src ="{{ profile_owner.userprofile.profile_pic.url }}" >

          <div class="media-body">

                <h2 class="account-heading"> {{ profile_owner.username | title }} </h2>
                <p class="text-secondary"> {{ profile_owner.email }} </p>

                {% if profile_owner ==  user %}
                    <a role="button" class="btn btn-warning" href="{% url 'user_app:changeinfo' %}"> Change Personal Info </a>
                    <br>
                    <br>
                    <a role="button" class="btn btn-warning" href="{% url 'user_app:password_change' %}"> Change Password </a>
                {% endif %}

          </div>

          <div>
            {% if posts %}
                {% for post in posts%}

                    <article class=" content-section">

                        <div class="article-metadata">
                          <img class="rounded-circle article-img" src="{{ post.author.userprofile.profile_pic.url }}">
                          <a class="mr-2" href="{% url 'blog:user-profile-details' post.author.username %}">{{ post.author }}</a>
                          <small class="text-muted">{{ post.date_posted }}</small>
                        </div>
                        <h2><a class="article-title" href="{% url 'blog:post-detail' post.id %}">{{ post.title }}</a></h2>
                        <p class="article-content">{{ post.content }}</p>

                    </article>
                {% endfor %}

            {% endif %}
          </div>


    </div>
{% endblock %}

blog/templates/blog/welcome_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>



</body>
</html>